### ISSUE TITLE
Error running pantera script

### ISSUE THREAD

**Issue by Ojwang-Biot** [piosierra/pantera#3]
Good evening.
I am trying to run pantera using the test.gfa file provided.
The following is the command I have tried

`pantera -g test.gfa -c 10 -o te_library`

However, I am getting the following error several times

```
cat: 'consen*.fa': No such file or directory
Error in nchar(seq) : 
  cannot coerce type 'closure' to vector of type 'character'
Calls: [ -> [.data.table -> eval -> eval -> nchar -> nchar
In addition: Warning messages:
1: In mclapply(rev(zones), process_zone, mc.preschedule = FALSE, mc.cores = opt$cores) :
  148 function calls resulted in an error
2: File '/tmp/RtmpOO0M6C/file1a7c6430d7cd' has size 0. Returning a NULL data.table. 
3: File '/tmp/RtmpOO0M6C/file1a7c1292a3ae' has size 0. Returning a NULL data.table. 
Execution halted
```
Please help

**Comment by piosierra** [comment]
Hi, can you try again without using the -c parameter? If that doesn't work, can you try with -c 2? Also, how much memory do you have available?

**Comment by Ojwang-Biot** [comment]
Hi,
I have 16gb of memory. I have tried the option you’ve suggested and still
getting the same error.

Kind regards
Paul

**Comment by piosierra** [comment]
Confirmed that the issue was a corrupt installation of CellaRepertorium, and that it can be installed with the current (3.19) version of Bioconductor.
