### ISSUE TITLE
which famdb library？

### ISSUE THREAD

**Issue by 1690078218** [piosierra/pantera#4]
Hello, I am currently using the test.gfa file you provided to reproduce the results. However, when using the Dfam TE tools, I am unsure which dataset from the famdb library to use for comparison and classification, resulting in many N (unknown bases) in the classification results. Could you please let me know which famdb library you used? I would greatly appreciate your help. Thank you!

**Comment by piosierra** [comment]
Hello, thanks for trying pantera. You can use the Astatotilapia calliptera library. Bear in mind that this is a toy gfa composed build from just one chromosome, to limit the file size, intended just as a way to check the instalation, and the model results may not match 100% the sequences in the library which have been produced with larger alignments from the whole genome.

**Comment by 1690078218** [comment]
thanks,I will try it

**Comment by piosierra** [comment]
Closed as no further comment.
